export const CONSTANTS = {
  // Change Engine
  BULK_CHANGE_THRESHOLD_ROWS: 1000,
  CHANGE_APPLIED_PK_LIST_MAX: 500,
  BACKUP_SNAPSHOT_TTL_DAYS: 7,

  // TUI
  TUI_TARGET_FPS: 30,
  TUI_FRAME_BUDGET_MS: 1000 / 30,

  // Sidecar Remote
  SIDECAR_JWT_EXPIRY_SECONDS: 3600,
  SIDECAR_RATE_LIMIT_RPS: 100,

  // Entity ID
  ENTITY_ID_PLAIN_ENABLED_DEFAULT_PROD: false,
  ENTITY_ID_PLAIN_ENABLED_DEFAULT_DEV: true,

  // Concurrency
  DB_P95_LATENCY_HARD_LIMIT_MS: 200,
  CONNECTION_POOL_THROTTLE_PCT: 80,

  // Key Rotation
  HMAC_KEY_ROTATION_DAYS: 30,

  // Projector
  PROJECTOR_MAX_RETRIES: 3,
  PROJECTOR_RETRY_BASE_MS: 1000,

  // WebSocket
  WS_MAX_QUEUE_SIZE: 100,
  WS_OVERLOAD_DELAY_THRESHOLD_MS: 3000,

  // Batch
  BATCH_SIZE_DEFAULT: 100,
  BATCH_SIZE_MIN: 10,
  BATCH_SIZE_MAX: 500,
} as const;
